[package]
name = "scmap-gen"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
clap.workspace = true
serde.workspace = true
serde_json.workspace = true

# Pull in the shared logic
streamdeck-sc-core = { path = "../core" }
